definitions:
  steps:
    - step: &build
        name: apk
        image: docker.cloudsmith.io/mars-bioimaging/infra/alpine-build-base:latest
        script:
          - mbi-require-tools 0
          - mbi-setup-cloudsmith-consumer ${CLOUDSMITH_SERIESB_READ_KEY}
          - mbi-install-tools alpine
          - mbi-build-apk
        artifacts:
          - out/*.apk
    - step: &publish
        name: publish
        image: docker.cloudsmith.io/mars-bioimaging/infra/alpine-build-base:latest
        script:
          - mbi-install-tools cloudsmith_alpine
          - mbi-cloudsmith-push -k$CLOUDSMITH_SERIESB_UPLOAD_API_KEY out/*.apk
            # N.B. The package version and other metadata are read from the built package itself.

pipelines:
  default:
    - step: *build
  tags:
    mbi-*:
    - step: *build
    - step: *publish
